library(dplyr)
#setwd("Desktop/Developer/DataScience/exploratory-data-analysis/exploratory-data-analysis-course-project-2/data/")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
TotalEmissions <- NEI %>% subset(fips == "24510") %>% group_by(year) %>% summarize(Em = sum(Emissions))
png("plot2.png")
barplot(TotalEmissions$Em,TotalEmissions$year,names.arg = TotalEmissions$year,xlab = "Year",ylab ="Total PM25 Emission (Tons)",ylim = c(0,4000))
dev.off()